#!/usr/bin/env python3
"""ligand_dummy_assembler
=================================

This standalone script augments organic ligands with dummy coordination atoms and
optionally performs a first-pass placement onto metal node templates.

Features
--------
* Pure NumPy implementation that only requires Python ≥ 3.10 and NumPy.
* Optional RDKit support (triggered with ``--use_rdkit`` and when RDKit is
  installed) to read SDF/MOL2/PDB formats and to validate atom/valence data.
* Optional SciPy support for optimal assignment via the Hungarian algorithm.
* Generates JSON/CSV summaries plus anchor rule files compatible with
  ``place_bbs.py`` and related tooling in the Tobacco 3.0 pipeline.
* Provides ``--examples`` helper that fabricates a tiny ligand set, an anchor
  specification, and a node template before executing the complete workflow.
* Includes lightweight self-tests (``--self_test``) to sanity-check critical
  geometry operations.

Input formats
-------------
* Ligands: ``.xyz`` (always supported) and ``.sdf/.mol2/.pdb`` when RDKit is
  available and explicitly requested.
* Anchor file: plain text. Each non-empty line follows
  ``pattern: idx0,idx1,idx2`` where ``pattern`` is a Unix shell glob that will
  be matched against the ligand file name. ``idx`` values are zero-based atom
  indices. Multiple anchor groups for the same pattern can be specified by
  separating blocks with ``;`` (e.g. ``lig*.xyz: 1,2; 10,11,12``). If a ligand
  is not covered, a virtual ``-1`` index (representing the centroid) is used.
* Template CSV: generated by ``scaled_embedding2coords.py``. The script reads
  the first three numeric columns as ``x,y,z`` coordinates and skips headers.

Output directory layout
-----------------------
``out_dummy`` is the default destination and contains:

``with_dummy/``
    XYZ files for each ligand with appended dummy atoms (``Du``).
``mapping.json``
    Records per-ligand anchors, generated dummy indices, geometry, and distance.
``anchors_rules.txt``
    Fully expanded anchor lines (``filename: idxs``) for downstream scripts.
``report.csv``
    Per-dummy diagnostics (actual distances, deviations, coordinates).
``placed/`` *(optional)*
    Ligands transformed towards template nodes when ``--assign_place``.
``assignment.csv`` *(optional)*
    Ligand ↔ node index matches and their associated costs.
``placed_summary.csv`` *(optional)*
    Rigid-body transforms (rotation in axis-angle form, translation, RMSD).

Coordinate conventions
----------------------
* Dummy directions derive from predefined coordination templates (tetrahedral,
  square-planar, octahedral, trigonal, linear) expressed as unit vectors.
* For every anchor group we build an orthonormal local frame. With ≥2 anchor
  atoms: ``A`` is the first index; ``x`` points from ``A`` towards the second
  index; ``z`` follows the cross product ``(A→B) × (A→C)`` when a third index
  exists, otherwise ``centroid − A``. ``y`` completes the right-handed system.
* Without anchors we treat the ligand centroid as origin, use PCA to estimate
  principal directions, and set ``x,y`` to the first two components.

Usage example
-------------
::

    python ligand_dummy_assembler.py \
        --ligand_dir ./ligs \
        --out_dir ./out_dummy \
        --geometry octahedral \
        --distance 1.8 \
        --anchors ./anchors.txt \
        --template_csv ./template_coords.csv \
        --assign_place

The script is resilient: it logs non-fatal errors per ligand, continues with the
remaining files, and summarises failures at the end. When optional dependencies
are missing it prints a downgrade notice and falls back to pure NumPy paths.
"""

from __future__ import annotations

import argparse
import csv
import fnmatch
import json
import logging
import math
import random
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

try:  # Optional SciPy (Hungarian assignment)
    from scipy.optimize import linear_sum_assignment  # type: ignore

    HAVE_SCIPY = True
except Exception:  # pragma: no cover - optional dependency
    HAVE_SCIPY = False

try:  # Optional RDKit support
    from rdkit import Chem  # type: ignore

    HAVE_RDKIT = True
except Exception:  # pragma: no cover - optional dependency
    HAVE_RDKIT = False


@dataclass
class LigandData:
    """Container for ligand atoms and coordinates."""

    atoms: List[str]
    coords: np.ndarray  # (N,3)
    source: Path


@dataclass
class AnchorGroupResult:
    """Outcome of placing dummy atoms for a single anchor group."""

    anchor_indices: List[int]
    anchor_point: np.ndarray
    rotation: np.ndarray
    dummy_coords: np.ndarray


def load_molecule_xyz(path: Path) -> LigandData:
    """Load atoms and coordinates from an XYZ file.

    Parameters
    ----------
    path : Path
        Location of the XYZ file.

    Returns
    -------
    LigandData
        Parsed atom symbols and coordinates.
    """

    try:
        with path.open("r", encoding="utf-8") as fh:
            lines = [line.strip() for line in fh if line.strip()]
    except OSError as exc:  # pragma: no cover - direct IO handling
        raise RuntimeError(f"Failed to read XYZ file '{path}': {exc}") from exc

    if not lines:
        raise ValueError(f"XYZ file '{path}' is empty")

    try:
        natoms = int(lines[0].split()[0])
        atom_lines = lines[2:2 + natoms]
    except (ValueError, IndexError):
        # Some XYZ omit the count/comment; fall back to using all lines
        atom_lines = lines

    atoms: List[str] = []
    coords: List[List[float]] = []
    for line in atom_lines:
        parts = line.split()
        if len(parts) < 4:
            continue
        atoms.append(parts[0])
        coords.append([float(parts[1]), float(parts[2]), float(parts[3])])

    if not atoms:
        raise ValueError(f"XYZ file '{path}' contains no atom records")

    return LigandData(atoms=atoms, coords=np.asarray(coords, dtype=float), source=path)


def load_molecule_rdkit(path: Path) -> LigandData:
    """Load a molecule using RDKit, returning atoms and a NumPy coordinate array."""

    if not HAVE_RDKIT:
        raise RuntimeError("RDKit requested but not available")

    mol: Optional[Chem.Mol]
    if path.suffix.lower() == ".sdf":
        supplier = Chem.SDMolSupplier(str(path), removeHs=False)
        mol = supplier[0] if supplier else None
    elif path.suffix.lower() == ".mol2":
        mol = Chem.MolFromMol2File(str(path), removeHs=False)
    elif path.suffix.lower() == ".pdb":
        mol = Chem.MolFromPDBFile(str(path), removeHs=False)
    else:
        raise ValueError(f"Unsupported RDKit format: {path.suffix}")

    if mol is None:
        raise ValueError(f"RDKit failed to parse '{path.name}'")

    conf = mol.GetConformer()
    atoms = [atom.GetSymbol() for atom in mol.GetAtoms()]
    coords = np.array([list(conf.GetAtomPosition(i)) for i in range(len(atoms))], dtype=float)
    return LigandData(atoms=atoms, coords=coords, source=path)


def save_molecule_xyz(path: Path, atoms: Sequence[str], coords: np.ndarray, comment: str = "") -> None:
    """Write atoms/coordinates to an XYZ file."""

    path.parent.mkdir(parents=True, exist_ok=True)
    natoms = len(atoms)
    lines = [str(natoms), comment or "generated by ligand_dummy_assembler"]
    for atom, xyz in zip(atoms, coords):
        lines.append(f"{atom:2s} {xyz[0]: .6f} {xyz[1]: .6f} {xyz[2]: .6f}")
    try:
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    except OSError as exc:  # pragma: no cover - IO handling
        raise RuntimeError(f"Failed to write XYZ file '{path}': {exc}") from exc


def parse_anchor_line(raw: str) -> Tuple[str, List[List[int]]]:
    """Parse a single anchor specification line."""

    pattern, indices = raw.split(":", 1)
    groups: List[List[int]] = []
    for chunk in indices.split(";"):
        chunk = chunk.strip()
        if not chunk:
            continue
        group = [int(tok.strip()) for tok in chunk.split(",") if tok.strip()]
        if group:
            groups.append(group)
    if not groups:
        groups.append([-1])  # sentinel for centroid
    return pattern.strip(), groups


def parse_anchors_file(path: Path, file_list: Sequence[Path]) -> Dict[Path, List[List[int]]]:
    """Return a mapping from file path to anchor index groups.

    Each matching ligand receives the expanded anchor groups defined by the
    first matching pattern. Multiple patterns can map to the same file; the
    first match wins to mimic shell glob precedence.
    """

    mapping: Dict[Path, List[List[int]]] = {}
    if not path:
        return mapping

    try:
        lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip() and not line.strip().startswith("#")]
    except OSError as exc:
        raise RuntimeError(f"Failed to read anchors file '{path}': {exc}") from exc

    parsed = [parse_anchor_line(line) for line in lines]

    for file_path in file_list:
        for pattern, groups in parsed:
            if fnmatch.fnmatch(file_path.name, pattern):
                mapping[file_path] = groups
                break

    return mapping


def normalize_vector(vec: np.ndarray) -> np.ndarray:
    """Return the normalised vector or a fallback axis if the vector vanishes."""

    norm = np.linalg.norm(vec)
    if norm < 1e-8:
        return np.array([1.0, 0.0, 0.0])
    return vec / norm


def orthonormalize(x_axis: np.ndarray, y_axis: np.ndarray, z_axis: np.ndarray) -> np.ndarray:
    """Return a 3×3 rotation matrix with orthonormal columns."""

    x = normalize_vector(x_axis)
    z = normalize_vector(z_axis - np.dot(z_axis, x) * x)  # Gram-Schmidt
    if np.linalg.norm(z) < 1e-8:
        # pick arbitrary axis orthogonal to x
        if abs(x[0]) < 0.9:
            z = np.cross(x, [1.0, 0.0, 0.0])
        else:
            z = np.cross(x, [0.0, 1.0, 0.0])
    z = normalize_vector(z)
    y = np.cross(z, x)
    y = normalize_vector(y)
    R = np.column_stack([x, y, z])
    return R


def build_local_frame(coords: np.ndarray, anchor_indices: Sequence[int]) -> Tuple[np.ndarray, np.ndarray]:
    """Construct a local reference frame for dummy atom placement.

    Parameters
    ----------
    coords : np.ndarray
        Cartesian coordinates of the ligand atoms (N×3).
    anchor_indices : Sequence[int]
        Atom indices defining the local axes. ``-1`` denotes the centroid.

    Returns
    -------
    Tuple[np.ndarray, np.ndarray]
        Anchor point ``A`` and a rotation matrix ``R_local`` whose columns are
        the orthonormal ``x``, ``y``, ``z`` axes.
    """

    if len(coords) == 0:
        raise ValueError("Cannot build a frame for an empty coordinate set")

    centroid = coords.mean(axis=0)

    indices = [idx for idx in anchor_indices if idx >= 0]
    if indices:
        for idx in indices:
            if idx >= len(coords):
                raise IndexError(f"Anchor index {idx} out of range for {len(coords)} atoms")
        anchor_point = coords[indices[0]]
        if len(indices) >= 2:
            vec_x = coords[indices[1]] - anchor_point
        else:
            vec_x = centroid - anchor_point
        if np.linalg.norm(vec_x) < 1e-8:
            vec_x = np.array([1.0, 0.0, 0.0])
        if len(indices) >= 3:
            vec_z = np.cross(coords[indices[1]] - anchor_point, coords[indices[2]] - anchor_point)
        else:
            vec_z = centroid - anchor_point
            if np.linalg.norm(vec_z) < 1e-8:
                vec_z = np.cross(vec_x, [0.0, 0.0, 1.0])
    else:
        # Centroid-based anchor
        anchor_point = centroid
        centered = coords - centroid
        cov = np.cov(centered.T)
        eigvals, eigvecs = np.linalg.eigh(cov)
        order = np.argsort(eigvals)[::-1]
        vec_x = eigvecs[:, order[0]]
        vec_y = eigvecs[:, order[1]] if len(order) > 1 else np.array([0.0, 1.0, 0.0])
        vec_z = np.cross(vec_x, vec_y)

    R_local = orthonormalize(vec_x, np.cross(vec_x, vec_z), vec_z)
    return anchor_point, R_local


def get_geometry_unit_vectors(name: str) -> np.ndarray:
    """Return unit direction vectors for a coordination geometry."""

    name = name.lower()
    if name == "tetrahedral":
        dirs = np.array([
            [1.0, 1.0, 1.0],
            [1.0, -1.0, -1.0],
            [-1.0, 1.0, -1.0],
            [-1.0, -1.0, 1.0],
        ])
    elif name == "square_planar":
        dirs = np.array([
            [1.0, 0.0, 0.0],
            [-1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, -1.0, 0.0],
        ])
    elif name == "octahedral":
        dirs = np.array([
            [1.0, 0.0, 0.0],
            [-1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, -1.0, 0.0],
            [0.0, 0.0, 1.0],
            [0.0, 0.0, -1.0],
        ])
    elif name == "trigonal":
        dirs = np.array([
            [1.0, 0.0, 0.0],
            [-0.5, math.sqrt(3) / 2.0, 0.0],
            [-0.5, -math.sqrt(3) / 2.0, 0.0],
        ])
    elif name == "linear":
        dirs = np.array([
            [1.0, 0.0, 0.0],
            [-1.0, 0.0, 0.0],
        ])
    else:
        raise ValueError(f"Unknown geometry template '{name}'")

    norms = np.linalg.norm(dirs, axis=1, keepdims=True)
    return dirs / norms


def place_dummy_atoms(anchor_point: np.ndarray, R_local: np.ndarray, unit_dirs: np.ndarray, distance: float) -> np.ndarray:
    """Generate dummy atom coordinates from a local frame."""

    offsets = unit_dirs * distance
    placed = anchor_point + offsets @ R_local.T
    return placed


def separate_close_points(points: np.ndarray, min_sep: float, iters: int = 20, step: float = 0.05) -> np.ndarray:
    """Iteratively push apart points that are closer than ``min_sep``."""

    if len(points) < 2:
        return points

    pts = points.copy()
    for _ in range(iters):
        moved = False
        for i in range(len(pts)):
            for j in range(i + 1, len(pts)):
                delta = pts[j] - pts[i]
                dist = np.linalg.norm(delta)
                if dist < 1e-8:
                    direction = np.random.normal(size=3)
                    dist = np.linalg.norm(direction)
                    if dist < 1e-8:
                        continue
                    delta = direction / dist * (min_sep * 0.5)
                    pts[i] -= delta
                    pts[j] += delta
                    moved = True
                elif dist < min_sep:
                    adjust = delta / dist * (min_sep - dist) * 0.5 * step
                    pts[i] -= adjust
                    pts[j] += adjust
                    moved = True
        if not moved:
            break
    return pts


def kabsch(P: np.ndarray, Q: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Compute the optimal rotation and translation aligning ``P`` to ``Q``.

    Returns rotation ``R`` and translation ``t`` such that ``P @ R.T + t``
    approximates ``Q``.
    """

    if P.shape != Q.shape:
        raise ValueError("Point sets must share the same shape for Kabsch")

    n = P.shape[0]
    if n == 0:
        return np.eye(3), np.zeros(3)

    centroid_P = P.mean(axis=0)
    centroid_Q = Q.mean(axis=0)
    P_centered = P - centroid_P
    Q_centered = Q - centroid_Q

    if n < 2:
        return np.eye(3), centroid_Q - centroid_P

    H = P_centered.T @ Q_centered
    U, _, Vt = np.linalg.svd(H)
    d = np.linalg.det(Vt.T @ U.T)
    D = np.diag([1.0, 1.0, np.sign(d)])
    R = Vt.T @ D @ U.T
    t = centroid_Q - centroid_P @ R
    return R, t


def greedy_assignment(cost_matrix: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Fallback greedy matching if SciPy is unavailable."""

    m, n = cost_matrix.shape
    used_rows = set()
    used_cols = set()
    assignments: List[Tuple[int, int]] = []
    flat_indices = np.argsort(cost_matrix, axis=None)
    for idx in flat_indices:
        r = idx // n
        c = idx % n
        if r in used_rows or c in used_cols:
            continue
        assignments.append((r, c))
        used_rows.add(r)
        used_cols.add(c)
        if len(assignments) == min(m, n):
            break
    rows = np.array([r for r, _ in assignments], dtype=int)
    cols = np.array([c for _, c in assignments], dtype=int)
    return rows, cols


def assign_to_nodes(lig_points: np.ndarray, node_points: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Match ligands to node coordinates using Euclidean distances."""

    if lig_points.size == 0 or node_points.size == 0:
        return np.array([], dtype=int), np.array([], dtype=int)
    cost = np.linalg.norm(lig_points[:, None, :] - node_points[None, :, :], axis=2)
    if HAVE_SCIPY:
        row_ind, col_ind = linear_sum_assignment(cost)
    else:
        row_ind, col_ind = greedy_assignment(cost)
    return row_ind, col_ind


def read_template_csv(path: Path) -> np.ndarray:
    """Read coordinates from a CSV file, skipping headers gracefully."""

    coords: List[List[float]] = []
    try:
        with path.open("r", encoding="utf-8") as fh:
            reader = csv.reader(fh)
            for row in reader:
                if not row:
                    continue
                try:
                    x, y, z = float(row[0]), float(row[1]), float(row[2])
                except ValueError:
                    continue  # skip header or malformed rows
                coords.append([x, y, z])
    except OSError as exc:
        raise RuntimeError(f"Failed to read template CSV '{path}': {exc}") from exc
    if not coords:
        raise ValueError(f"Template CSV '{path}' contains no coordinates")
    return np.asarray(coords, dtype=float)


def format_axis_angle(R: np.ndarray) -> Tuple[float, np.ndarray]:
    """Convert rotation matrix to axis-angle representation."""

    angle = math.acos(max(-1.0, min(1.0, (np.trace(R) - 1.0) / 2.0)))
    if abs(angle) < 1e-8:
        return 0.0, np.array([1.0, 0.0, 0.0])
    axis = np.array([
        R[2, 1] - R[1, 2],
        R[0, 2] - R[2, 0],
        R[1, 0] - R[0, 1],
    ])
    axis = axis / (2 * math.sin(angle))
    return angle, axis


def run_self_tests() -> None:
    """Execute a handful of self-tests to validate critical helpers."""

    # Test dummy placement distance
    coords = np.array([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])
    anchor_point, frame = build_local_frame(coords, [0, 1, 2])
    dirs = get_geometry_unit_vectors("linear")
    placed = place_dummy_atoms(anchor_point, frame, dirs, 2.0)
    distances = np.linalg.norm(placed - anchor_point, axis=1)
    assert np.allclose(distances, 2.0, atol=1e-3)

    # Test orthonormality
    dot_matrix = frame.T @ frame
    assert np.allclose(dot_matrix, np.eye(3), atol=1e-6)

    # Assignment size
    lig_pts = np.array([[0, 0, 0], [1, 0, 0]])
    node_pts = np.array([[0.1, 0, 0], [1.1, 0, 0]])
    rows, cols = assign_to_nodes(lig_pts, node_pts)
    assert len(rows) == 2 and len(cols) == 2

    # XYZ atom count update
    tmp = Path(tempfile.mkdtemp()) / "test.xyz"
    save_molecule_xyz(tmp, ["H", "Du"], np.array([[0, 0, 0], [1, 0, 0]]))
    loaded = load_molecule_xyz(tmp)
    assert len(loaded.atoms) == 2
    tmp.unlink(missing_ok=True)

    print("Self-tests passed.")


def create_example_dataset(tmpdir: Path) -> Tuple[Path, Path, Path]:
    """Generate a minimal example dataset under ``tmpdir``."""

    lig_dir = tmpdir / "ligs"
    lig_dir.mkdir()
    lig1 = lig_dir / "lig_a.xyz"
    lig1.write_text(
        """5
ligand A
C 0.0 0.0 0.0
H 0.0 0.0 1.0
H 1.0 0.0 0.0
H 0.0 1.0 0.0
O -1.0 0.0 0.0
""",
        encoding="utf-8",
    )
    lig2 = lig_dir / "lig_b.xyz"
    lig2.write_text(
        """6
ligand B
C 0.1 0.0 0.0
C -0.9 0.0 0.0
H 0.1 1.0 0.0
H 0.1 -1.0 0.0
O -0.9 0.0 1.0
O -0.9 0.0 -1.0
""",
        encoding="utf-8",
    )
    anchors = tmpdir / "anchors.txt"
    anchors.write_text("lig_*.xyz: 0,2,3", encoding="utf-8")
    template = tmpdir / "template.csv"
    template.write_text("0,0,0\n3,0,0\n", encoding="utf-8")
    return lig_dir, anchors, template


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Augment ligands with dummy coordination atoms.")
    parser.add_argument("--ligand_dir", type=Path, help="Directory containing ligand files (.xyz required).")
    parser.add_argument("--out_dir", type=Path, default=Path("out_dummy"), help="Output directory.")
    parser.add_argument("--geometry", type=str, default="octahedral", help="Coordination geometry template.")
    parser.add_argument("--distance", type=float, default=1.8, help="Dummy atom distance from anchor (Å).")
    parser.add_argument("--anchors", type=Path, default=None, help="Optional anchor configuration file.")
    parser.add_argument("--template_csv", type=Path, default=None, help="Optional node template CSV.")
    parser.add_argument("--assign_place", action="store_true", help="Perform node assignment and placement.")
    parser.add_argument("--du_per_anchor", type=int, default=None, help="Override number of dummy atoms per anchor.")
    parser.add_argument("--min_separation", type=float, default=0.8, help="Minimum dummy-dummy separation (Å).")
    parser.add_argument("--use_rdkit", action="store_true", help="Enable RDKit IO paths when RDKit is installed.")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for reproducible jitters.")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging output.")
    parser.add_argument("--examples", action="store_true", help="Generate and run a miniature example dataset.")
    parser.add_argument("--self_test", action="store_true", help="Run internal self-tests and exit.")

    args = parser.parse_args(argv)

    if args.self_test:
        run_self_tests()
        return 0

    if args.examples:
        tmpdir = Path(tempfile.mkdtemp(prefix="lig_dummy_example_"))
        lig_dir, anchor_file, template_csv = create_example_dataset(tmpdir)
        print(f"Example data generated under {tmpdir}")
        example_args = [
            "--ligand_dir", str(lig_dir),
            "--out_dir", str(tmpdir / "out"),
            "--geometry", args.geometry,
            "--distance", str(args.distance),
            "--anchors", str(anchor_file),
            "--template_csv", str(template_csv),
            "--assign_place",
            "--verbose",
        ]
        return main(example_args)

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO, format="[%(levelname)s] %(message)s")

    random.seed(args.seed)
    np.random.seed(args.seed)

    if args.use_rdkit and not HAVE_RDKIT:
        logging.warning("--use_rdkit requested but RDKit is unavailable; falling back to XYZ parsing.")

    ligand_dir = args.ligand_dir
    if not ligand_dir.exists() or not ligand_dir.is_dir():
        logging.error("Ligand directory '%s' does not exist or is not a directory.", ligand_dir)
        return 1

    supported_ext = [".xyz"]
    if args.use_rdkit and HAVE_RDKIT:
        supported_ext.extend([".sdf", ".mol2", ".pdb"])

    ligand_files = sorted([p for p in ligand_dir.iterdir() if p.suffix.lower() in supported_ext])
    if not ligand_files:
        logging.error("No supported ligand files found in '%s'.", ligand_dir)
        return 1

    if args.anchors:
        anchors_map = parse_anchors_file(args.anchors, ligand_files)
    else:
        anchors_map = {}

    unit_dirs = get_geometry_unit_vectors(args.geometry)
    if args.du_per_anchor is not None:
        unit_dirs = unit_dirs[: args.du_per_anchor]
        if len(unit_dirs) < args.du_per_anchor:
            raise ValueError("Requested more dummy atoms than provided by geometry template")

    out_dir = args.out_dir
    with_dummy_dir = out_dir / "with_dummy"
    placed_dir = out_dir / "placed"
    out_dir.mkdir(parents=True, exist_ok=True)
    with_dummy_dir.mkdir(parents=True, exist_ok=True)
    if args.assign_place:
        placed_dir.mkdir(parents=True, exist_ok=True)

    mapping_records = []
    anchors_rules_lines: List[str] = []
    report_rows: List[List[str]] = [["file", "anchor_group", "dummy_label", "target_distance", "actual_distance", "deviation", "x", "y", "z"]]
    assignment_rows: List[List[str]] = [["ligand", "node_index", "cost"]]
    placed_summary_rows: List[List[str]] = [["ligand", "node_index", "axis_angle_deg", "axis_x", "axis_y", "axis_z", "translation_x", "translation_y", "translation_z", "rmsd"]]

    lig_centroids: List[np.ndarray] = []
    lig_dummy_sets: List[np.ndarray] = []
    lig_anchor_points: List[np.ndarray] = []
    lig_atoms: List[List[str]] = []
    lig_coords: List[np.ndarray] = []
    lig_files_processed: List[Path] = []

    failures: List[Tuple[str, str]] = []

    for lig_path in ligand_files:
        try:
            if lig_path.suffix.lower() == ".xyz" or not (args.use_rdkit and HAVE_RDKIT):
                ligand = load_molecule_xyz(lig_path)
            else:
                ligand = load_molecule_rdkit(lig_path)
        except Exception as exc:
            logging.error("Failed to load '%s': %s", lig_path.name, exc)
            failures.append((lig_path.name, str(exc)))
            continue

        anchor_groups = anchors_map.get(lig_path, [[-1]])

        new_atoms = list(ligand.atoms)
        new_coords = ligand.coords.copy()
        dummy_indices: List[List[int]] = []
        dummy_coords_all: List[np.ndarray] = []
        anchor_results: List[AnchorGroupResult] = []

        for group_idx, anchor_group in enumerate(anchor_groups):
            try:
                anchor_point, frame = build_local_frame(ligand.coords, anchor_group)
            except Exception as exc:
                logging.error("%s: invalid anchor group %s (%s)", lig_path.name, anchor_group, exc)
                failures.append((lig_path.name, f"anchor {anchor_group}: {exc}"))
                break
            placed = place_dummy_atoms(anchor_point, frame, unit_dirs, args.distance)
            dummy_coords_all.append(placed)
            anchor_results.append(AnchorGroupResult(anchor_group, anchor_point, frame, placed))
            start_idx = len(new_atoms)
            dummy_indices.append(list(range(start_idx, start_idx + len(placed))))
            for idx in range(len(placed)):
                new_atoms.append("Du")
            new_coords = np.vstack([new_coords, placed])
            anchors_rules_lines.append(f"{lig_path.name}: {','.join(str(i) for i in anchor_group)}")
        else:
            # Only executed if the inner loop did not break (i.e. no anchor failure)
            if len(dummy_coords_all) > 1 and args.min_separation > 0:
                combined = np.vstack(dummy_coords_all)
                adjusted = separate_close_points(combined, args.min_separation)
                new_coords[-len(combined) :] = adjusted
                # Update anchor_results dummy coords
                offset = 0
                for res in anchor_results:
                    count = len(res.dummy_coords)
                    res.dummy_coords = adjusted[offset : offset + count]
                    offset += count

            save_comment = f"source={lig_path.name} geometry={args.geometry} distance={args.distance:.3f}"
            save_molecule_xyz(with_dummy_dir / f"{lig_path.stem}_with_dummy.xyz", new_atoms, new_coords, comment=save_comment)

            for group_idx, res in enumerate(anchor_results):
                for local_idx, coord in enumerate(res.dummy_coords):
                    dist = np.linalg.norm(coord - res.anchor_point)
                    deviation = abs(dist - args.distance)
                    report_rows.append([
                        lig_path.name,
                        str(group_idx),
                        f"Du{local_idx + 1}",
                        f"{args.distance:.6f}",
                        f"{dist:.6f}",
                        f"{deviation:.6f}",
                        f"{coord[0]:.6f}",
                        f"{coord[1]:.6f}",
                        f"{coord[2]:.6f}",
                    ])

            mapping_records.append(
                {
                    "file": lig_path.name,
                    "anchors": anchor_groups,
                    "dummy_indices": dummy_indices,
                    "geometry": args.geometry,
                    "distance": args.distance,
                }
            )

            lig_centroids.append(np.mean(np.vstack([res.dummy_coords for res in anchor_results]), axis=0))
            lig_dummy_sets.append(np.vstack([res.dummy_coords for res in anchor_results]))
            lig_anchor_points.append(anchor_results[0].anchor_point if anchor_results else ligand.coords.mean(axis=0))
            lig_atoms.append(new_atoms)
            lig_coords.append(new_coords)
            lig_files_processed.append(lig_path)

    mapping_json = out_dir / "mapping.json"
    mapping_json.write_text(json.dumps(mapping_records, indent=2), encoding="utf-8")
    (out_dir / "anchors_rules.txt").write_text("\n".join(anchors_rules_lines) + "\n", encoding="utf-8")
    with (out_dir / "report.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerows(report_rows)

    if args.template_csv and args.assign_place and lig_dummy_sets:
        try:
            node_points = read_template_csv(args.template_csv)
        except Exception as exc:
            logging.error("Failed to read template CSV: %s", exc)
            node_points = np.empty((0, 3))
        if node_points.size > 0:
            lig_points = np.vstack(lig_centroids)
            row_ind, col_ind = assign_to_nodes(lig_points, node_points)
            for lig_idx, node_idx in zip(row_ind, col_ind):
                cost = np.linalg.norm(lig_points[lig_idx] - node_points[node_idx])
                assignment_rows.append([lig_files_processed[lig_idx].name, str(node_idx), f"{cost:.6f}"])
                dummy_points = lig_dummy_sets[lig_idx]
                if len(dummy_points) >= 3:
                    target = node_points[node_idx] + get_geometry_unit_vectors(args.geometry)[: len(dummy_points)] * args.distance
                    R, t = kabsch(dummy_points, target)
                    transformed_coords = lig_coords[lig_idx] @ R.T + t
                    placed_path = placed_dir / f"{lig_files_processed[lig_idx].stem}_placed.xyz"
                    save_molecule_xyz(placed_path, lig_atoms[lig_idx], transformed_coords, comment=f"placed node={node_idx}")
                    angle, axis = format_axis_angle(R)
                    rmsd = np.sqrt(np.mean(np.sum((dummy_points @ R.T + t - target) ** 2, axis=1)))
                else:
                    R = np.eye(3)
                    t = node_points[node_idx] - lig_points[lig_idx]
                    transformed_coords = lig_coords[lig_idx] + t
                    placed_path = placed_dir / f"{lig_files_processed[lig_idx].stem}_placed.xyz"
                    save_molecule_xyz(placed_path, lig_atoms[lig_idx], transformed_coords, comment=f"placed node={node_idx}")
                    angle, axis = 0.0, np.array([1.0, 0.0, 0.0])
                    rmsd = float(np.linalg.norm(dummy_points + t - (node_points[node_idx])))
                placed_summary_rows.append([
                    lig_files_processed[lig_idx].name,
                    str(node_idx),
                    f"{math.degrees(angle):.6f}",
                    f"{axis[0]:.6f}",
                    f"{axis[1]:.6f}",
                    f"{axis[2]:.6f}",
                    f"{t[0]:.6f}",
                    f"{t[1]:.6f}",
                    f"{t[2]:.6f}",
                    f"{rmsd:.6f}",
                ])
            with (out_dir / "assignment.csv").open("w", newline="", encoding="utf-8") as fh:
                csv.writer(fh).writerows(assignment_rows)
            with (out_dir / "placed_summary.csv").open("w", newline="", encoding="utf-8") as fh:
                csv.writer(fh).writerows(placed_summary_rows)
    elif args.assign_place:
        logging.warning("Assignment requested but template CSV unavailable or ligands failed; skipping placement.")

    success_count = len(lig_files_processed)
    failure_count = len(failures)
    if failure_count:
        logging.warning("Completed with %d successes and %d failures.", success_count, failure_count)
        for name, reason in failures:
            logging.warning("  %s: %s", name, reason)
    else:
        logging.info("Processed %d ligands successfully.", success_count)

    return 0 if success_count > 0 else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
